version: "3.8"
name: hogwarts_admin
services:
  db:
    container_name: hogwarts_db
    image: mysql:8.0.34
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:3306
    volumes:
      #  - ./data:/var/lib/mysql # for data
      - DATA:/var/lib/mysql # for data
volumes:
  DATA: